name: foil
description: >
  Wrap a widget with Foil, providing a rainbow shimmer
  that twinkles as the accelerometer moves as well as
  tons of neat gradient features.
version: 0.9.0+1
repository: https://github.com/Zabadam/foil
issue_tracker: https://github.com/Zabadam/foil/issues

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  # spectrum: ^0.2.1+1
  sensors_plus: ^1.0.1

dev_dependencies:
  spectrum:
    path: ../spectrum/

flutter: null
